language: python
python:
  - "3.5"
  - "3.6"
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - python -m pytest --cov=tests/
after_success:
  - codecov
env:
  global:
    - PGPORT=8001
