version: '2'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      DB_PORT: 5432
      DB_HOST: db
    volumes:
      - data:/var/lib/postgresql/data
  test_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test_db
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - test_data:/var/lib/postgresql/test_data
    ports:
      - 5432:8002
  test_web:
    image: nginx
    ports:
      - 80:8003
volumes:
  data:
  test_data:
